env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1

dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements_build.txt

script:
  - BOTO_CONFIG=/dev/null py.test -v
